Traceback (most recent call last):
  File "C:\Users\ADM\miniconda3\envs\ml_venv\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\ADM\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\ADM\miniconda3\envs\ml_venv\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\ADM\miniconda3\envs\ml_venv\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\ADM\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\ADM\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\ADM\miniconda3\envs\ml_venv\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig = px.bar(df_top10_renewable, 
             x='total_renewable', 
             y='country', 
             text='total_renewable', 
             title='Top 10 pa√≠ses con mayor consumo de energ√≠as renovables per c√°pita (1990 - 2022)',
             labels={'total_renewable': 'Consumo Total de Energ√≠a (TWh)', 'country': 'Pa√≠s'},
             orientation='h',
             color='total_renewable', 
             color_continuous_scale='YlOrBr')

fig.update_traces(texttemplate='%{text:.3s}', textposition='outside')
fig.update_layout(xaxis_title='Consumo Total de Energ√≠a (TWh)', 
                  yaxis_title='Pa√≠s',
                  showlegend=False)

fig.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[16], line 1[0m
[1;32m----> 1[0m fig [38;5;241m=[39m px[38;5;241m.[39mbar([43mdf_top10_renewable[49m, 
[0;32m      2[0m              x[38;5;241m=[39m[38;5;124m'[39m[38;5;124mtotal_renewable[39m[38;5;124m'[39m, 
[0;32m      3[0m              y[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcountry[39m[38;5;124m'[39m, 
[0;32m      4[0m              text[38;5;241m=[39m[38;5;124m'[39m[38;5;124mtotal_renewable[39m[38;5;124m'[39m, 
[0;32m      5[0m              title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mTop 10 pa√≠ses con mayor consumo de energ√≠as renovables per c√°pita (1990 - 2022)[39m[38;5;124m'[39m,
[0;32m      6[0m              labels[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mtotal_renewable[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mConsumo Total de Energ√≠a (TWh)[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mcountry[39m[38;5;124m'[39m: [38;5;124m'[39m[38;5;124mPa√≠s[39m[38;5;124m'[39m},
[0;32m      7[0m              orientation[38;5;241m=[39m[38;5;124m'[39m[38;5;124mh[39m[38;5;124m'[39m,
[0;32m      8[0m              color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mtotal_renewable[39m[38;5;124m'[39m, 
[0;32m      9[0m              color_continuous_scale[38;5;241m=[39m[38;5;124m'[39m[38;5;124mYlOrBr[39m[38;5;124m'[39m)
[0;32m     11[0m fig[38;5;241m.[39mupdate_traces(texttemplate[38;5;241m=[39m[38;5;124m'[39m[38;5;124m%[39m[38;5;132;01m{text:.3s}[39;00m[38;5;124m'[39m, textposition[38;5;241m=[39m[38;5;124m'[39m[38;5;124moutside[39m[38;5;124m'[39m)
[0;32m     12[0m fig[38;5;241m.[39mupdate_layout(xaxis_title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mConsumo Total de Energ√≠a (TWh)[39m[38;5;124m'[39m, 
[0;32m     13[0m                   yaxis_title[38;5;241m=[39m[38;5;124m'[39m[38;5;124mPa√≠s[39m[38;5;124m'[39m,
[0;32m     14[0m                   showlegend[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[1;31mNameError[0m: name 'df_top10_renewable' is not defined

